apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Testing for the 1st time
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: test@snapp.com
  lifecycle: experimental


